### ISSUE TITLE
Comparison of Primary Operating System for Higher Salary Data Scientists

### ISSUE THREAD

**Issue by vaibhavgupta2499** [JosephArcila/Data-Science-Blog-Post#1]
Hey Joseph, as individuals with higher salary packages, tend to work on MacOS as it is expensive, and hence, a status symbol. Hence, I think the main reason for usage of MacOS by high salary Data scientists is this only, and not any difference of utilities between Windows, Linux or MacOS.

**Comment by JosephArcila** [comment]
I use Windows 10 and haven't faced any significant issues, but have heard a lot that MACs have better experience overall and significantly much more processing power battery performance.

**Comment by vaibhavgupta2499** [comment]
Yes, that must have been the case, but I also feel that Windows environment is equally productive, plus a lot of open source utilities are available. Thanks for clarification.
